[package]
name = "tuiba"
description = "Game Boy Advance emulator running in your terminal"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
homepage.workspace = true
readme.workspace = true
keywords.workspace = true
categories.workspace = true

[[bin]]
name = "tuiba"
path = "src/main.rs"

[dependencies]
tuiba-core.workspace = true
thiserror.workspace = true
ratatui.workspace = true
crossterm.workspace = true

[lints]
workspace = true
